SELECT
I.SYMBOL,
    SUM(T.CHANGE_IN_OI) AS TOTAL_OI_CHANGE
FROM TRADES T
INNER JOIN CONTRACTS C
    ON T.CONTRACT_ID = C.CONTRACT_ID
INNER JOIN  INSTRUMENTSI
    ON C.INSTRUMENT_ID = I.INSTRUMENT_ID
GROUP BY I.SYMBOL
ORDER BY TOTAL_OI_CHANGE DESC
LIMIT 10;

